# This is the configuration file for Netlify.
# It tells Netlify where to find our serverless function.

[build]
  # This command is not strictly necessary for a static site, but it's good practice.
  command = "echo 'Build complete'"
  # This is the directory where our serverless function code lives.
  functions = "netlify/functions"
  # The directory that contains our main index.html file.
  publish = "."

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
