version: '3.8'

services:
  chaos-test:
    build:
      context: .
      dockerfile: Dockerfile
    image: chaos-engineering:latest
    container_name: chaos-test-runner
    
    # Resource limits to prevent host exhaustion
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '1.0'
          memory: 1G
    
    # Environment configuration
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - SCENARIO=${SCENARIO:-cascade-failure}
      - AGENT_COUNT=${AGENT_COUNT:-6}
    
    # Mount points
    volumes:
      - ./chaos_reports:/app/chaos_reports
      - ./config.yaml:/app/config.yaml:ro
    
    # Command override
    command: [
      "--scenario", "${SCENARIO:-cascade-failure}",
      "--agents", "${AGENT_COUNT:-6}",
      "--log-level", "${LOG_LEVEL:-INFO}"
    ]
    
    # Network configuration
    networks:
      - chaos-net
    
    # Security options
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /var/tmp

  # Optional: Prometheus for metrics
  prometheus:
    image: prom/prometheus:latest
    container_name: chaos-prometheus
    profiles:
      - monitoring
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - chaos-net

  # Optional: Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    container_name: chaos-grafana
    profiles:
      - monitoring
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./grafana/datasources:/etc/grafana/provisioning/datasources:ro
    networks:
      - chaos-net

networks:
  chaos-net:
    driver: bridge

volumes:
  prometheus-data:
  grafana-data: