name: 🧠 Detect Intent Keyword in Any Test

on:
  push:
    paths:
      - 'microservices/ambiguity/ambiguous_request_examples/**'
  workflow_dispatch:

jobs:
  keyword-check:
    runs-on: ubuntu-latest
    steps:
      - name: Grep "follow up" across all input files
        run: |
          if grep -i "follow up" microservices/ambiguity/ambiguous_request_examples/*.json; then
            echo "✅ Found intent-like phrase"
          else
            echo "❌ No matching phrase found"
            exit 1
          fi

