name: Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black flake8 isort
    - name: Check formatting with black
      run: |
        black --check --verbose . || echo "Formatting issues found"
    - name: Apply black formatting (optional)
      run: |
        black .
    - name: Check imports with isort
      run: |
        isort --check-only --profile black . || echo "Import issues found"
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || echo "Linting issues found"
