name: IP Protection

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ip-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install tools
        run: |
          pip install safety bandit
      
      - name: License check
        run: |
          echo "Starting license check..."
          pip freeze > deps.txt
          echo "Dependencies saved to deps.txt"
          
          if grep -qi "gpl" deps.txt; then
            echo "WARNING: GPL dependency found"
          else
            echo "No GPL dependencies detected"
          fi
      
      - name: Copyright check
        run: |
          echo "Checking copyright headers..."
          
          total=0
          with_copyright=0
          
          for file in $(find . -name "*.py" | head -20); do
            total=$((total + 1))
            if head -5 "$file" | grep -qi "copyright"; then
              with_copyright=$((with_copyright + 1))
            fi
          done
          
          echo "Files checked: $total"
          echo "With copyright: $with_copyright"
      
      - name: Security scan
        run: |
          echo "Running security scan..."
          safety check || echo "Safety check completed"
          
          echo "Checking for secrets..."
          if find . -name "*.py" -exec grep -l "password\|secret\|key" {} \; | head -3; then
            echo "Potential secrets found - please review"
          else
            echo "No obvious secrets detected"
          fi
      
      - name: Generate report
        run: |
          echo "Generating IP protection report..."
          
          echo "# IP Protection Report" > report.md
          echo "" >> report.md
          echo "Generated: $(date)" >> report.md
          echo "Repository: $GITHUB_REPOSITORY" >> report.md
          echo "" >> report.md
          echo "## Summary" >> report.md
          echo "- License check: Completed" >> report.md
          echo "- Copyright check: Completed" >> report.md
          echo "- Security scan: Completed" >> report.md
          echo "" >> report.md
          echo "## Status" >> report.md
          echo "IP protection scan completed successfully." >> report.md
          
          echo "Report generated successfully"
      
      - uses: actions/upload-artifact@v4
        with:
          name: ip-protection-report
          path: |
            report.md
            deps.txt
