name: 🧠 Run Ambiguity Audit

on:
  push:
    paths:
      - 'microservices/ambiguity/**'
  workflow_dispatch:

jobs:
  run-ambiguity-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Create Placeholder CLI if not present
        run: |
          mkdir -p microservices/ambiguity
          echo "print('🧠 Running ambiguity audit stub')" > microservices/ambiguity/cli_resolver.py

      - name: Execute Ambiguity CLI
        run: |
          python microservices/ambiguity/cli_resolver.py
