name: 🔧 Sanity Check

on:
  push:
    branches:
      - main
      - master
      - "**"
  workflow_dispatch:

jobs:
  run-sanity-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Run Python version + list files
        run: |
          echo "✅ Python version:"
          python --version

          echo "🧠 Listing Neuron files:"
          find . -type f

