name: Test Neuron Framework

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']  # Start with just one version to simplify debugging
      fail-fast: false  # Allow all tests to run even if one fails
    timeout-minutes: 10  # Add a timeout to prevent hanging jobs

    steps:
    - uses: actions/checkout@v3
      name: Check out repository code
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest
        pip install -e .
        
    - name: List installed packages and directory structure
      run: |
        pip list
        ls -la
        
    - name: Run basic import test
      run: |
        python -c "import neuron; print(f'Neuron imported successfully, version: {getattr(neuron, \"__version__\", \"unknown\")}')"
        
    - name: Test with pytest
      run: |
        pytest -v
