name: Test Neuron Framework

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']  # Start with just one version
      fail-fast: false
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v3
      name: Check out repository code
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Display Python version
      run: python -V
      
    - name: Display directory structure
      run: |
        ls -la
        find . -type f -name "*.py" | sort
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest
        
    - name: Install package in development mode
      run: |
        pip install -e .
        
    - name: Verify import
      run: |
        python -c "import neuron; print(f'Neuron imported successfully, version: {neuron.__version__}')"
        
    - name: Test with pytest (if tests exist)
      run: |
        if [ -d "tests" ]; then
          pytest -v tests/
        else
          echo "No tests directory found. Skipping pytest."
        fi
